<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Accepted usernames arestandard_userlock_91a402</name>
   <tag></tag>
   <elementGuidId>41260581-d299-4598-9d8e-6409e11d1ad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login_credentials']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login_credentials</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a703f162-c750-4b99-b6c7-7fe3ff74deef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_credentials</value>
      <webElementGuid>1657087d-f633-4355-8bbf-3fe5c43e91b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login_credentials</value>
      <webElementGuid>0452e485-da04-448a-a358-2ccb859a3844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accepted usernames are:standard_userlocked_out_userproblem_userperformance_glitch_usererror_user</value>
      <webElementGuid>2c2a6805-4f1b-4534-8095-7b3a094e4de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_credentials&quot;)</value>
      <webElementGuid>637bb6d0-dc52-49b5-a543-58af47293a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>60131978-daf6-4c90-8240-b9b66be3a30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_credentials</value>
      <webElementGuid>f35ed750-4ead-4f98-92cb-08e2199668c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login_credentials</value>
      <webElementGuid>76cfd52a-0c6a-42f7-bbb4-3714a6d63e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accepted usernames are:standard_userlocked_out_userproblem_userperformance_glitch_usererror_user</value>
      <webElementGuid>eb1974dd-5586-4c3b-95ee-a5ec61a6922a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_credentials&quot;)</value>
      <webElementGuid>157f8fce-f9bb-4157-b188-161b23e38fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cd97fbd0-f159-40c7-8d11-1a216369b78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_credentials</value>
      <webElementGuid>496bc431-9187-4b82-bd88-a777a46c6281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login_credentials</value>
      <webElementGuid>ae36dffb-e9f8-4197-98f9-8cc6be44c0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accepted usernames are:standard_userlocked_out_userproblem_userperformance_glitch_usererror_user</value>
      <webElementGuid>6c890510-4fcd-4b79-b08c-5ea92e351353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_credentials&quot;)</value>
      <webElementGuid>28e94f58-1325-4437-bfe1-1eddf3620d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2a9b82ee-97b0-4bb0-bd6d-9ed2a1d69ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_credentials</value>
      <webElementGuid>54988a3e-1de0-4111-9993-92da2c60c7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login_credentials</value>
      <webElementGuid>d80039f4-9c4c-4476-b052-a84e20045930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accepted usernames are:standard_userlocked_out_userproblem_userperformance_glitch_usererror_user</value>
      <webElementGuid>664d5119-1cb5-473d-b0f2-dc065fe03e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_credentials&quot;)</value>
      <webElementGuid>e5bca9ea-9e9a-4a43-9ba7-3a27c6194806</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='login_credentials']</value>
      <webElementGuid>e83ac307-db31-492d-858e-0ce79a550fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div</value>
      <webElementGuid>b8d18cb1-5fba-41b2-a636-da6686e1e849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Swag Labs'])[2]/following::div[10]</value>
      <webElementGuid>ece77055-92f7-4867-b334-cc6d65dc87c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='standard_user']/parent::*</value>
      <webElementGuid>7a99598b-6f96-478f-8052-b68a7eabf7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>96ed7d00-f179-418b-b339-a90e18399a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'login_credentials' and (text() = 'Accepted usernames are:standard_userlocked_out_userproblem_userperformance_glitch_usererror_user' or . = 'Accepted usernames are:standard_userlocked_out_userproblem_userperformance_glitch_usererror_user')]</value>
      <webElementGuid>08461e30-8eb4-40fe-bc72-d9e436045809</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
